### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by nightsoundars** [or-dvir/EasySettings#2]
Hello! I want to contribute on your project with making logo design. What do you think about it?

**Comment by or-dvir** [comment]
@nightsoundars sure that sounds good!
but this is a library not an app... so would the logo be just for the github page?
anyways... your offer is appreciated and accepted

**Comment by nightsoundars** [comment]
https://drive.google.com/open?id=1QKj3CmpIwacoIiwjGUMgKnOGocvnEYyh
Hi, I've done a study I hope you like...

**Comment by or-dvir** [comment]
not bad, but i think the wrench represents manual labor and in combination with the gear icon it looks more like a mechanics logo as opposed to software based settings of an app.

do you think you can come up with something more suitable?

**Comment by or-dvir** [comment]
@nightsoundars closing the issue until further updates
