### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by iqbalza** [or-dvir/EasySettings#3]
Hey, thanks for the library.
I'm using a dark theme for my app, so i need to use custom colored text. How can i do that?

**Comment by iqbalza** [comment]
I've managed to change text color by overriding the styles.

**Comment by Raudius** [comment]
What styles affect what text? 
The primary color seems to change the summary but I cant figure out what I value to override to change the title texts.

**Comment by or-dvir** [comment]
I can't member by heart and I won't be able to check for the next 2 weeks.
You could download the sample app and look there
