### ISSUE TITLE
Suggestion: Overload setIcon to accept drawable

### ISSUE THREAD

**Issue by katomm** [or-dvir/EasySettings#4]
Hello,

I may have overlooked something but, when building the array, it would be tremendously helpful to overload the setIcon method to accept also a drawable instead of only a resource id like: 
```
new BasicSettingsObject.Builder(SETTINGS_KEY_EXAMPLE, getString(R.string.pref_example))
                .setIcon(new ExampleDrawable(this).icon(ExampleDrawable.MyIconName))
                .build() 
```

As a workaround one can dig into the image view to achieve this:
```
View root = findViewById(settingsObject.getRootId());
ImageView imageView = root.findViewById(settingsObject.getImageViewIconId());
imageView.setImageDrawable(drawable);
```

**Comment by or-dvir** [comment]
sure. i will add this in the near future.
in the meantime it should be easy enough to extend the builder and add that function to it.

**Comment by or-dvir** [comment]
added in [version 1.1.3](https://github.com/or-dvir/EasySettings/releases/tag/1.1.3).

note that `setIcon(@Nullable @DrawableRes Integer iconId)` will **override** this new method
