### ISSUE TITLE
Issue: No subscriber event found

### ISSUE THREAD

**Issue by deepakkumarece14** [or-dvir/EasySettings#5]
All the things are working properly while I was working locally. But When I uploaded the app on play store the app got crashed when Setting Activity was opened, showing the issue of no Subscriber event found.

Then I found that because I enabled the proguard, it removed the subscriber methods because It was unused as we don't have to call it anywhere in the Activity. Also, I can't disable proguard.
Is there anything that can help?

**Comment by or-dvir** [comment]
this is an `EventBus` issue with proguard and not an issue with this library.
the solution may be found [here](http://greenrobot.org/eventbus/documentation/proguard)

**Comment by deepakkumarece14** [comment]
Thanks, for the help.
I have tried this already by keeping all the class with @keep annotation but it gave me another error.

**Comment by or-dvir** [comment]
unfortunately i dont really know anything about proguard so i can't really help you. perhaps you can ask your question on the `EventBus` github page [here](https://github.com/greenrobot/EventBus)
