### ISSUE TITLE
Importing with jitpack

### ISSUE THREAD

**Issue by crocodile** [or-dvir/EasySettings#6]
I was unable to import the project following the description:
> implementation 'com.github.or-dvir.EasySettings:easysettings-basic:1.1.3
>  implementation 'com.github.or-dvir.EasySettings:easysettings-dialogs:1.1.3

but it worked like this:
> implementation 'com.github.or-dvir.EasySettings:1.1.3

Any idea why this is the case? Thanks

**Comment by or-dvir** [comment]
please post the full error message

**Comment by or-dvir** [comment]
closed due to inactivity
