### ISSUE TITLE
Store data in sqlite

### ISSUE THREAD

**Issue by psohm** [or-dvir/EasySettings#7]
It would be useful to store data in a sqlite database
Is it possible to integrate external saving ?

**Comment by or-dvir** [comment]
why would it be useful? this doesnt make any sense.
databases are meant to hold a large and complex amount of data where settings are just basic types (numbers and strings). also accessing a database is a much more expensive operation than accessing SharedPreferences (and accessing that data could happen a lot during an apps' life cycle).

can you please explain why you would want to do this?

**Comment by psohm** [comment]
Sure
I have an application which store config file for one company
I'd like to configure now multiple company and also to sync it with a server

**Comment by or-dvir** [comment]
how big of a configuration file? if not too big, you can possibly convert it to json and then store that as a string.
it sounds like the "regular" way of storing settings/preferences does not suit your needs, and this library is meant to be as close to the "regular" way as possible.

**Comment by psohm** [comment]
i think it is a good idea to store in a json file.

how would do you proceed, would you store in shared pref file and then migrate it in json ? or would you directly store in json with a lib ?

**Comment by or-dvir** [comment]
i meant store the json as string (which you can save to shared preferences), not a file.
i dont know the specifics of your app requirements and how this configuration file is built, but maybe instead of in a file you can save those configurations as a json string and then save that string to shared preferences
