### ISSUE TITLE
Dependency on eventbus is not good idea for a library

### ISSUE THREAD

**Issue by pellyadolfo** [or-dvir/EasySettings#9]
I like the project but, a library, ideally, should have not external dependencies, or the less possible. 

Eventbus is a library that imposes a pattern so it will make difficult adoption. On the other hand, it looks an unnecessary dependency IMHO.

**Comment by or-dvir** [comment]
you are absolutely correct.
this is an old library by now and in desperate need of an update. however i dont have the time to deal with this in the near future...

my apologies
